### ISSUE TITLE
Goals for this fork?

### ISSUE THREAD

**Issue by joelmccracken** [s-mage/rush#11]
We talked briefly at one point about this project, but I was again
toying with a ruby shell, and am thinking about this problem again.

I have a very specific direction I would like to take Rush. I want to
make it a friendly, highly interactive shell -- much more than it
currently is. I want to use Ruby to make the shell an even more
enjoyable environment.

To that end, I ask: what are your goals for Rush? Personally, I am
interested in creative freedom and the ability to explore the
problem. I don't want to invest in Rush if our goals are very
different. For example, I see little value in the remote/ssh
replacement aspects of
Rush, and would probably completely remove these features.

**Comment by s-mage** [comment]
Hard to disagree with your goals. "Friendly" is very wide definition. For
me rush is OK now, but it's because I rewrote it. Features that I
personally use work well, but that's not mean that I will not fix or
implement something else.

So, have you some concrete suggestions what to do to make rush better?

**Comment by joelmccracken** [comment]
I spent a few minutes experimenting with the fork. Here are some thoughts:

Rush doesn't have a `help` command or `rush --help`. While trying to figure
this out, I stumbled on a bug where Rush was trying to iterate over each
item in my PATH, and raised an exception for each that no longer existed.

I'd like to see a 'tutorial' or 'tour' help section which would highlight
what makes the Ruby shell so good.

I would probably remove the idea of "boxes", or make it another gem. It
just seems foreign to me.

Conversely, I'd like Rush to support launching a 'server' so another REPL
could be connected to the same process over something like telnet. This
probably would make sense only with a unix socket for security reasons.

I would like to experiment with a two command modes: a 'ruby' mode and a
'shell' mode. The ruby mode takes just ruby, but the shell mode would
include some parsing and support some small bash-like syntax.

I'd like to see some "edit" commands which launch EDITOR for easily
customizing the environment. Looking at 'commands.rb', it looks like a
simple 'edit' function that launched EDITOR would be great, for example.

Related to the last two items, I'd like Rush to behave somewhat more Unixy
-- launch commands with fork, rely upon standard environment variables,
etc. I want to replace my shell with Rush, and I just don't think that can
happen today.

Thoughts?

**Comment by s-mage** [comment]
>  I would like to experiment with a two command modes: a 'ruby' mode and a 'shell' mode. The ruby mode takes just ruby, but the shell mode would include some parsing and support some small bash-like syntax.

This is what I definitely don't want to do. You can use pry if you want that division or run bash right from rush, like `system 'bash'' or so. On other suggestions I will think tomorrow.

**Comment by s-mage** [comment]
So, let's see.

> I would probably remove the idea of "boxes", or make it another gem. It just seems foreign to me.
No, I like it. But I think I will add something like box.cd to work inside context of the box. It's not always convenient to write everytime box.gad; box.gc 'blah'; box.gps 

> Conversely, I'd like Rush to support launching a 'server' so another REPL could be connected to the same process over something like telnet. This probably would make sense only with a unix socket for security reasons.
Interesting idea, really. I don't know how will I use it but you can try to implement it yourself :)

> I'd like to see some "edit" commands which launch EDITOR for easily customizing the environment.
No problem, it would be easy.

**Comment by joelmccracken** [comment]
Cool. I'm /probably/ going to keep experimenting separately, then. But it does sound like we could work together on some things! I'm going to close the issue, thanks for letting me know what your thoughts are.
