### ISSUE TITLE
pry-based ruby shell

### ISSUE THREAD

**Issue by ctrlok** [s-mage/rush#12]
Hi. Maybe it is a good idea - use pry for some shell-based actions and some additional modules for replacing bash functionality?

**Comment by ctrlok** [comment]
I mean something like: 
``` ps ax | $_.each_line | puts "nginx are here" if $_.scan(/nginx/).any?``` Maybe with other syntax.

**Comment by s-mage** [comment]
I saw such project already. Will show a bit later.

**Comment by s-mage** [comment]
https://github.com/tombenner/ru

**Comment by s-mage** [comment]
I like the way that rush works. It's just ruby, when you need to manipulate with come data, you can do:

```
output_of('bash_command').each_line { |x| p 'boom' if x.include? 'some_string' }
```
