### ISSUE TITLE
Command encapsulation

### ISSUE THREAD

**Issue by Leo2807** [s-mage/rush#13]
I have a suggestion: encapsulating commands so you can use ruby code to execute a command.

This would be useful to automate commands that don't have a (useful) library.

It could be implemented by having a command task class and have the user create a child class and overriding a flags hash and the run function. (Maybe a parse function to handle the output.)

**Comment by s-mage** [comment]
Hi, thank you for your suggestion, but I need some example of that process.

**Comment by Leo2807** [comment]
That's right, I forgot them. Sorry.

```Ruby

class OpenFile < Rush::Command

  def initialize()
    @options = {
      :a = false # false is the default value for this argument
    }
    @command = "open"
  end

end

openFile = OpenFile.new

# Will run `open -a Atom ./file.rb`
openfile.run({
  :a => "Atom"
  }, "./file.rb")
  
end

```

**Comment by s-mage** [comment]
Couldn't it be better to just pass some hash of parameters? Like

```
  home['some_file.rb'].open { a: 'Atom', b: 'Some B' }
  #=> open -a Atom -b Some B ./some_file.rb

  home['some_file.rb'].vim { other: '+55' }
  #=> vim ./some_file.rb +55
```

**Comment by Leo2807** [comment]
That's way better. I wouldn't add those commands to the `File` class though. I'd have a function on the file class. Like:
```Ruby
home['some_file.rb'].cmd :git, { help: true}
#=> `git --help`
```
Or override an operator:
```Ruby
home['some_file.rb'] << :git, { help: true}
#=> `git --help`
```
In that way the file class stays clean.

**Comment by s-mage** [comment]
Oh, that's cool. Going to implement it.

**Comment by s-mage** [comment]
```
home['.vimrc'].vim { other: '+55', x: true, u: 'other_vimrc', cmd: 'ls' }
```

So, now you can do this now.

**Comment by Leo2807** [comment]
Yaaaaay
